name: doc-page-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # or 3.10, specify a suitable Python version
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn   # for SMOTE and handling imbalanced data
  - xgboost
  - lightgbm
  - matplotlib
  - seaborn
  - joblib
  - jupyterlab        # or jupyter, to run notebooks in VSCode/Jupyter
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - jupyterlab
  - pyinstaller
  - pip:
      - tensorflow==2.15.1
      - tensorflow-metal==1.1.0
      - keras-tuner==1.3.5